<?php
require_once __DIR__ . '/../modelos/loginModelo.phtml';
require_once __DIR__ . '/../vistas/errorVista.php'; 
require_once __DIR__ . '/../vistas/loginVista.php'; 

class LoginControlador {
    private $loginModelo;
    private $vistaError;
    private $vistaLogin;

    public function __construct() {
        $this->loginModelo = new loginModelo();
        $this->vistaLogin = new loginAdminVista(); 
        $this->vistaError = new errorVista();
    }
    public function mostrarFormulario() {
        $this->vistaLogin->mostrarVistaDelLogin();
    }
    public function procesarLogin() {
        if(empty($_POST['nombre']) || empty($_POST['contrasenia'])) {
            return $this->vistaError->mostrarError("Por favor, complete todos los campos.");
        }

        $nombre = $_POST['nombre'];
        $contrasenia = $_POST['contrasenia'];

        $admin = $this->loginModelo->obtenerAdminPorNombre($nombre);
        //si se loguea bien lo mandamos a el inicio
        if ($admin && $admin->contrasenia === $contrasenia) {
            session_start();
            $_SESSION["id_admin"] = $admin->id_admin;
            $_SESSION["nombre"] = $admin->nombre;
            header("Location: ". BASE_URL);
            die();
        } else {
            $this->vistaError->mostrarError("Usuario o contraseña incorrecta");
        }
    }
    public function cerrarSesion() {
        session_start();    
        session_destroy();  
        header("Location: " . BASE_URL); 
        die();
    }
}