<?php
require_once __DIR__ . '/../modelos/fleteModelo.phtml';
require_once __DIR__ . '/../vistas/errorVista.php'; 

class LoginControlador {
    private $modelo;
    private $vistaError;
    private $vistaLogin;

    public function __construct() {
        $this->modelo = new fleteModelo();
        $this->vistaLogin = new vistaLoginAdmin(); 
        $this->vistaError = new errorVista();
    }
    public function mostrarFormulario() {
        $this->vistaLogin->mostrarVistaDelLogin();
    }
    public function procesarLogin() {
        if(empty($_POST['nombre']) || empty($_POST['contrasenia'])) {
            return $this->vistaError->mostrarError("Por favor, complete todos los campos.");
        }

        $nombre = $_POST['nombre'];
        $contrasenia = $_POST['contrasenia'];

        $admin = $this->modelo->obtenerAdminPorNombre($nombre);
        //si se loguea bien lo mandamos a el inicio
        if ($admin && $admin->contrasenia === $contrasenia) {
            $_SESSION["id_admin"] = $admin->id_admin;
            $_SESSION["nombre"] = $admin->nombre;
            header("Location: ". BASE_URL);
        } else {
            $this->vistaError->mostrarError("Usuario o contraseña incorrecta");
        }
    }
}