<?php
class fleteModelo{
    private $db;
    public function __construct() {
        $this->db = new PDO('mysql:host=localhost;dbname=fletestransporte;charset=utf8', 'root', '');
    }
    public function conseguirObjetos(){
        $accion = $this->db->prepare('SELECT * FROM `pedidos`');
        
        $accion -> execute();
        $objetos = $accion->fetchAll(PDO::FETCH_OBJ);
        
        return $objetos;
    }
    public function PedidoPorId($id){
        $accion = $this->db-> prepare('SELECT * FROM pedidos WHERE id_pedido = ?');
        $accion -> execute([$id]);
        $pedido = $accion->fetch(PDO::FETCH_OBJ);
        return $pedido;
    }
    public function obtenerAdminPorNombre($nombre){
        $accion= $this->db-> prepare('Select * FROM administradores WHERE nombre = ? ');
        $accion-> execute([$nombre]);
        $administrador = $accion->fetch(PDO::FETCH_OBJ);
        return $administrador;

    }
    public function conseguirClientes() {
        $accion = $this->db->prepare('SELECT * FROM clientes');
        $accion->execute();
        $clientes = $accion->fetchAll(PDO::FETCH_OBJ);
        return $clientes;
    }
    public function insertarPedido($estado, $origen, $destino, $fechaentrega, $precio, $id_cliente, $imagen_url) {
        $accion = $this->db->prepare('INSERT INTO pedidos (estado, origen, destino, fechaentrega, precio, id_cliente, imagen_url) VALUES (?, ?, ?, ?, ?, ?, ?)');
        $accion->execute([$estado, $origen, $destino, $fechaentrega, $precio, $id_cliente, $imagen_url]);
        
        return $this->db->lastInsertId();
    }

    // Eliminar un pedido específico usando su id
    public function eliminarPedido($id) {
        $accion = $this->db->prepare('DELETE FROM pedidos WHERE id_pedido = ?');
        $accion->execute([$id]);
    }

    // Actualiza los datos de un pedido existente
    public function actualizarPedido($id, $estado, $origen, $destino, $fechaentrega, $precio, $id_cliente, $imagen_url) {
        $accion = $this->db->prepare('UPDATE pedidos SET estado = ?, origen = ?, destino = ?, fechaentrega = ?, precio = ?, id_cliente = ?, imagen_url = ? WHERE id_pedido = ?');
        $accion->execute([$estado, $origen, $destino, $fechaentrega, $precio, $id_cliente, $imagen_url, $id]);
    }
}